### ISSUE TITLE
Vulnerability tracking

### ISSUE THREAD

**Issue by deleonio** [leanupjs/leanup#54]

**Comment by martinoppitz** [comment]
**pathval** inside @leanup/cli@1.0.46 › @leanup/cli-core-test@1.0.46 › chai@4.2.0 › pathval@1.1.0

- [ ] Vulnerability: https://snyk.io/test/npm/pathval/1.1.0
- [ ] Issue: https://github.com/chaijs/pathval/pull/60
- [ ] PR: https://github.com/chaijs/pathval/pull/60
  - [ ] merged
- [ ] Fixed package available
- [ ] Leanup updated

**Comment by martinoppitz** [comment]
**pathval** inside @leanup/cli@1.0.46 › @leanup/cli-core-test@1.0.46 › chai@4.2.0 › pathval@1.1.0

- [x] Vulnerability: https://snyk.io/test/npm/nightwatch@1.5.1
- [x] Issue:
  - https://github.com/nightwatchjs/nightwatch/issues/2533
- [x] PR:
  - https://github.com/nightwatchjs/nightwatch/pull/2537
    - [ ] reviewed
    - [ ] merged
- [ ] Fixed package available
- [ ] Leanup updated

**Comment by martinoppitz** [comment]
**webpack-pwa-manifest** inside
- webpack-pwa-manifest@4.2.0 › jimp@0.6.8 › @jimp/types@0.6.8 › @jimp/jpeg@0.6.8 › jpeg-js@0.3.7
- webpack-pwa-manifest@4.2.0 › jimp@0.6.8 › @jimp/custom@0.6.8 › @jimp/core@0.6.8 › mkdirp@0.5.1 › minimist@0.0.8

- [x] Vulnerability: https://snyk.io/test/npm/webpack-pwa-manifest/4.2.0
- [ ] Issue:
  - 
- [ ] PR:
  - 
    - [ ] reviewed
    - [ ] merged
- [ ] Fixed package available
- [ ] Leanup updated

**Comment by martinoppitz** [comment]
- @leanup/cli-core-test@1.0.46 › mocha@8.2.1 › yargs@13.3.2 › y18n@4.0.0
- @leanup/cli-core-test@1.0.46 › nyc@15.1.0 › yargs@15.4.1 › y18n@4.0.0
---
- [x] Vulnerability: https://snyk.io/test/npm/@leanup/cli-core-test/1.0.46
- [x] Issue:
  - https://github.com/mochajs/mocha/issues/4513
  - https://github.com/istanbuljs/nyc/issues/1367
- [ ] PR:
  - https://github.com/
    - [ ] passed
    - [ ] reviewed
    - [ ] merged
  - https://github.com/
    - [x] passed
    - [x] reviewed
    - [x] merged
- [x] Fixed package available
- [x] Leanup updated
